version: "3.7"
services:
  test:
    image: nginx
    ports:
     - "6298:80"
    deploy:
      replicas: 1
    labels:
      # - com.roo.host:test.sfpl.io:80:http=http://test_test:6298
      OriginHosts: test.sfpl.io
      OriginScheme: https
      OriginPort: 443
      DestinationHost: test_test
      DestinationScheme: http
      DestinationPort: 6298
    
networks:
  forenet:
    driver: overlay
    external: true          